_commit: 3.0.0
_src_path: https://github.com/hypermedia-app/creta-template-app.git
apis:
- api
app_name: view-builder
author: Zazuko GmbH
debugger_port: '32272'
email: no-reply@zazuko.com
generate_ui: true
node_version: '16'
project_name: View Builder API
repository: https://github.com/zazuko/ssz-view-builder
ui_path: app
vocabs: []

