PREFIX rdfs: <http://www.w3.org/2000/01/rdf-schema#>
PREFIX hydra: <http://www.w3.org/ns/hydra/core#>
PREFIX cube: <https://cube.link/>
PREFIX rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#>
PREFIX schema: <http://schema.org/>

CONSTRUCT {
  <urn:ssz:deep-props> a hydra:Collection ;
    hydra:member ?prop .
  ?prop rdfs:label ?prop
}
where {
  select distinct ?prop {
    {
      SELECT ?prop
      {
        ?cube cube:observationSet/cube:observation ?observation .

        ?observation <{DIMENSION}> ?observationValue .
        ?observationValue ?prop ?any .

        FILTER (?prop NOT IN (schema:inDefinedTermSet, rdf:type ))
      }
      limit 500
    }
  }
}
