name: Release

on:
  push:
    branches:
      - main

jobs:
  release:
    name: Prepeare release
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          # This makes Actions fetch all Git history so that Changesets can generate changelogs with the correct commits
          fetch-depth: 0

      - uses: actions/setup-node@v2.4.0
        with:
          node-version: 16

      - run: yarn

      - name: Generate token
        id: generate_token
        uses: tibdex/github-app-token@v1
        with:
          app_id: ${{ secrets.GH_APP_ID }}
          private_key: ${{ secrets.GH_PRIVATE_KEY }}

      - name: Create Release Pull Request
        uses: changesets/action@v1
        env:
          GITHUB_TOKEN: ${{ steps.generate_token.outputs.token }}
        with:
          commit: "chore: release"
          title: "Merge to release"

  tags:
    name: Create tags
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Generate token
        id: generate_token
        uses: tibdex/github-app-token@v1
        with:
          app_id: ${{ secrets.GH_APP_ID }}
          private_key: ${{ secrets.GH_PRIVATE_KEY }}

      - name: Tag API
        uses: butlerlogic/action-autotag@1.1.2
        with:
          root: apps/api
          tag_prefix: view-builder-api/v
        env:
          GITHUB_TOKEN: ${{ steps.generate_token.outputs.token }}

      - name: Tag UI
        uses: butlerlogic/action-autotag@1.1.2
        with:
          root: apps/www
          tag_prefix: view-builder-ui/v
        env:
          GITHUB_TOKEN: ${{ steps.generate_token.outputs.token }}

      - name: Tag APP
        uses: butlerlogic/action-autotag@1.1.2
        with:
          root: apps/app
          tag_prefix: view-builder-app/v
        env:
          GITHUB_TOKEN: ${{ steps.generate_token.outputs.token }}
